### ISSUE TITLE
PA Review: Heroku Deployment

### ISSUE THREAD

**Issue by vanden** [vanden/ewere#1]
https://ewere.herokuapp.com/

Hard to see what to add as checkboxes, other than 

- [x] Yes, it is hosted

(Should this be postponed until there is a real app to look at? I've put it here, now, as we were told this should be our first MVP.)

**Comment by niartenyaw** [comment]
I can't mark this off until there is a successful push, but we can work through that. Can you add the heroku link to the top of your wiki as well? Thanks!

**Comment by vanden** [comment]
Hi Aaron,

It was up when I submitted the PA. I didn't realize it, but I broke it, in
between. To the best of my belief, it is up, now.

Best,

Brian



On Jan 31, 2018 5:57 PM, "niartenyaw" <notifications@github.com> wrote:

I can't mark this off until there is a successful push, but we can work
through that. Can you add the heroku link to the top of your wiki as well?
Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/vanden/ewere/issues/1#issuecomment-362133190>, or mute
the thread

**Comment by niartenyaw** [comment]
Sweet, looks good! Feel free to close.
