### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by vanden** [vanden/ewere#4]
- [ ]  Backend: DB, model, controller, views
- [ ]  Redux Loop: ajax, actions, reducer
- [ ]  Smooth, bug-free navigation
- [ ]  Presentational Components
- [ ]  Styling
- [ ]  Adequate and appropriate seeds
- [ ]  Demo user signin?

I do think that it would be better if on the login form, the user did not have to re-enter their email address. I'm behind enough, though, that I thought it best to put in the PA with that wrinkle un-ironed.

**Comment by niartenyaw** [comment]
Sweet! A few very small things, feel free to fix these whenever. As soon as they are done, this MVP is complete!

## Functionality

- [ ] You don't need to have users put in an `email` for `login`, only `signup`

## Styling

- [ ] Let's make the `Sign Up` and `Login` buttons the same height as the `Demo User`
- [ ] Add some `padding` to the form input boxes to give the text some space

**Comment by vanden** [comment]
For the form input boxes, do you mean horizontal or vertical padding? (Or, both?)

**Comment by niartenyaw** [comment]
I would try padding for both
