### ISSUE TITLE
PA Review: Teams

### ISSUE THREAD

**Issue by vanden** [vanden/ewere#5]
- [ ]  Backend: DB, model, controller, views
- [ ]  Redux Loop: ajax, actions, reducer
- [ ]  Smooth, bug-free navigation
- [ ]  Presentational Components
- [ ]  Styling
- [ ]  Adequate and appropriate seeds
- [ ]  Demo user signin?

**Comment by niartenyaw** [comment]
Looks great! Feel free to mark this as closed
